version: '3'
services:
  api:
    build: .
    ports:
     - "8080:8080"
    depends_on:
    - postgres
    image: magneto
  postgres:
    image: postgres:11
    container_name: "postgres"
    ports:
      - "5432:5432"
