version: '3'
services:
  api:
    image: magneto
    build: .
    ports:
     - "8080:8080"
    depends_on:
    - postgres
    - redis
    - rabbit
  postgres:
    image: postgres:11
    container_name: "postgres"
    ports:
      - "5432:5432"
  redis:
    image: redis
    container_name: "redis"
    ports:
      - "6379:6379"
  rabbit:
    image: rabbitmq
    container_name: "rabbit"
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "admin"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"